### ISSUE TITLE
Cannot edit user information

### ISSUE THREAD

**Issue by AchielC** [VTK-Revue/revue-flask-server#3]
Ik wil mijn voor en achternaam aanpassen via: Account -> Profiel
Ik geef een nieuwe voor- of achternaam in en als ik dan op save klik lijkt het in orde. Maar als ik dan terug naar mijn mijn profiel ga kijken staan er nog steeds de oude values.

**Comment by ToonDeb** [comment]
Ik heb hetzelfde
