### ISSUE TITLE
Mail komt niet aan

### ISSUE THREAD

**Issue by rduflou** [VTK-Revue/revue-flask-server#6]
Mail gestuurd naar sgreivers@revue.vtk.be en dit terug gekregen:

This is an automatically generated Delivery Status Notification.
Delivery to the following recipients failed.
       sgreivers@revue.vtk.be

Moet het sgreivers@dev.revue.vtk.be zijn?

**Comment by FKint** [comment]
bc55a69923338c8e816032d4d63692cec0200a4a fixed this issue.
38eb023cf8290d742479e83bf6e231d05268ae31 now shows the address (if set).
please note: sgreivers@DEV.revue.vtk.be
