### ISSUE TITLE
Traag en server error

### ISSUE THREAD

**Issue by ToonDeb** [VTK-Revue/revue-flask-server#9]
De website is heel traag, en als ik mijn wachtoord en gebruikersnaam invul en op login klik, krijg ik na lange tijd een 500-internal server error:
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by FKint** [comment]
We hebben het over dev.revue.vtk.be?

**Comment by ToonDeb** [comment]
ah, nee, sorry

ik zat op revue.vtk.behttp://revue.vtk.be

Op di 20 sep. 2016 om 21:21 schreef Floris Kint <notifications@github.com<mailto:notifications@github.com>>:
We hebben het over dev.revue.vtk.behttp://dev.revue.vtk.be?

**Comment by FKint** [comment]
Is inderdaad ook een probleem, maar dat heeft niks met de ontwikkeling van
deze applicatie te maken. Bedankt om te melden wel!
